import { Component } from '@angular/core';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent {
  snippets = {
    'menu': {
      htmlCode: '<div class=\"card w-56\">\n  <ul class=\"menu\">\n    <li><a>Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card w-56\">\n  <ul className=\"menu\">\n    <li><a>Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'menu with icons and badge': {
      htmlCode: '<div class=\"card w-72\">\n  <ul class=\"menu\">\n    <li><a><span class=\"material-icons-round\">home</span>Home</a></li>\n    <li><a><span class=\"material-icons-round\">info</span>Info</a></li>\n    <li>\n      <a>\n        <span class=\"material-icons-round\">watch_later</span>\n        Watch Later\n        <span class=\"badge badge-error\">+999</span>\n      </a>\n    </li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card w-72\">\n  <ul className=\"menu\">\n    <li><a><span className=\"material-icons-round\">home</span>Home</a></li>\n    <li><a><span className=\"material-icons-round\">info</span>Info</a></li>\n    <li>\n      <a>\n        <span className=\"material-icons-round\">watch_later</span>\n        Watch Later\n        <span className=\"badge badge-error\">+999</span>\n      </a>\n    </li>\n  </ul>\n</div>',
    },
    'menu with icons only': {
      htmlCode: '<div class=\"card\">\n  <ul class=\"menu\">\n    <li><a><span class=\"material-icons-round\">home</span></a></li>\n    <li><a><span class=\"material-icons-round\">info</span></a></li>\n    <li><a><span class=\"material-icons-round\">watch_later</span></a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card\">\n  <ul className=\"menu\">\n    <li><a><span className=\"material-icons-round\">home</span></a></li>\n    <li><a><span className=\"material-icons-round\">info</span></a></li>\n    <li><a><span className=\"material-icons-round\">watch_later</span></a></li>\n  </ul>\n</div>',
    },
    'menu with title': {
      htmlCode: '<div class=\"card w-56\">\n  <ul class=\"menu\">\n    <li class=\"menu-title\">Title</li>\n    <li><a>Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card w-56\">\n  <ul className=\"menu\">\n    <li className=\"menu-title\">Title</li>\n    <li><a>Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'menu with title as parent': {
      htmlCode: '<div class=\"card w-56\">\n  <ul class=\"menu\">\n    <li>\n      <span class=\"menu-title\">Title</span>\n      <ul>\n        <li><a>Link 1</a></li>\n        <li><a>Link 2</a></li>\n        <li><a>Link 3</a></li>\n      </ul>\n    </li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card w-56\">\n  <ul className=\"menu\">\n    <li>\n      <span className=\"menu-title\">Title</span>\n      <ul>\n        <li><a>Link 1</a></li>\n        <li><a>Link 2</a></li>\n        <li><a>Link 3</a></li>\n      </ul>\n    </li>\n  </ul>\n</div>',
    },
    'menu with submenu': {
      htmlCode: '<div class=\"card w-60\">\n  <ul class=\"menu\">\n    <li><a>Link 1</a></li>\n    <li>\n      <a>Parent</a>\n      <ul>\n        <li><a>Child 1</a></li>\n        <li><a>Child 2</a></li>\n        <li>\n          <a>Parent</a>\n          <ul>\n            <li><a>Child 1</a></li>\n            <li><a>Child 2</a></li>\n            <li><a>Child 3</a></li>\n          </ul>\n        </li>\n      </ul>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card w-60\">\n  <ul className=\"menu\">\n    <li><a>Link 1</a></li>\n    <li>\n      <a>Parent</a>\n      <ul>\n        <li><a>Child 1</a></li>\n        <li><a>Child 2</a></li>\n        <li>\n          <a>Parent</a>\n          <ul>\n            <li><a>Child 1</a></li>\n            <li><a>Child 2</a></li>\n            <li><a>Child 3</a></li>\n          </ul>\n        </li>\n      </ul>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'collapsible submenu': {
      htmlCode: '<div class=\"card w-56\">\n  <ul class=\"menu\">\n    <li><a>Link 1</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n          <li>\n            <details>\n              <summary>collapsed</summary>\n              <ul>\n                <li><a>Child 1</a></li>\n                <li><a>Child 2</a></li>\n              </ul>\n            </details>\n          </li>\n        </ul>\n      </details>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card w-56\">\n  <ul className=\"menu\">\n    <li><a>Link 1</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n          <li>\n            <details>\n              <summary>collapsed</summary>\n              <ul>\n                <li><a>Child 1</a></li>\n                <li><a>Child 2</a></li>\n              </ul>\n            </details>\n          </li>\n        </ul>\n      </details>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'horizontal menu': {
      htmlCode: '<div class=\"card\">\n  <ul class=\"menu menu-horizontal\">\n    <li><a>Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card\">\n  <ul className=\"menu menu-horizontal\">\n    <li><a>Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'horizontal menu with icons and badge': {
      htmlCode: '<div class=\"card\">\n  <ul class=\"menu menu-horizontal\">\n    <li><a><span class=\"material-icons-round\">home</span>Home</a></li>\n    <li><a><span class=\"material-icons-round\">info</span>Info</a></li>\n    <li>\n      <a>\n        <span class=\"material-icons-round\">watch_later</span>\n        Watch Later\n        <span class=\"badge badge-error\">+999</span>\n      </a>\n    </li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card\">\n  <ul className=\"menu menu-horizontal\">\n    <li><a><span className=\"material-icons-round\">home</span>Home</a></li>\n    <li><a><span className=\"material-icons-round\">info</span>Info</a></li>\n    <li>\n      <a>\n        <span className=\"material-icons-round\">watch_later</span>\n        Watch Later\n        <span className=\"badge badge-error\">+999</span>\n      </a>\n    </li>\n  </ul>\n</div>',
    },
    'horizontal menu with icons only': {
      htmlCode: '<div class=\"card\">\n  <ul class=\"menu menu-horizontal\">\n    <li><a><span class=\"material-icons-round\">home</span></a></li>\n    <li><a><span class=\"material-icons-round\">info</span></a></li>\n    <li><a><span class=\"material-icons-round\">watch_later</span></a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card\">\n  <ul className=\"menu menu-horizontal\">\n    <li><a><span className=\"material-icons-round\">home</span></a></li>\n    <li><a><span className=\"material-icons-round\">info</span></a></li>\n    <li><a><span className=\"material-icons-round\">watch_later</span></a></li>\n  </ul>\n</div>',
    },
    'horizontal menu with submenu': {
      htmlCode: '<div class=\"card\">\n  <ul class=\"menu menu-horizontal\">\n    <li><a>Link 1</a></li>\n    <li>\n      <a>Parent</a>\n      <ul>\n        <li><a>Child 1</a></li>\n        <li><a>Child 2</a></li>\n        <li>\n          <a>Parent</a>\n          <ul>\n            <li><a>Child 1</a></li>\n            <li><a>Child 2</a></li>\n            <li><a>Child 3</a></li>\n          </ul>\n        </li>\n      </ul>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card\">\n  <ul className=\"menu menu-horizontal\">\n    <li><a>Link 1</a></li>\n    <li>\n      <a>Parent</a>\n      <ul>\n        <li><a>Child 1</a></li>\n        <li><a>Child 2</a></li>\n        <li>\n          <a>Parent</a>\n          <ul>\n            <li><a>Child 1</a></li>\n            <li><a>Child 2</a></li>\n            <li><a>Child 3</a></li>\n          </ul>\n        </li>\n      </ul>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'horizontal collapsible submenu': {
      htmlCode: '<div class=\"card\">\n  <ul class=\"menu menu-horizontal\">\n    <li><a>Link 1</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n          <li>\n            <details>\n              <summary>collapsed</summary>\n              <ul>\n                <li><a>Child 1</a></li>\n                <li><a>Child 2</a></li>\n              </ul>\n            </details>\n          </li>\n        </ul>\n      </details>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"card\">\n  <ul className=\"menu menu-horizontal\">\n    <li><a>Link 1</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n          <li>\n            <details>\n              <summary>collapsed</summary>\n              <ul>\n                <li><a>Child 1</a></li>\n                <li><a>Child 2</a></li>\n              </ul>\n            </details>\n          </li>\n        </ul>\n      </details>\n    </li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'menu with colors and active state': {
      htmlCode: '<!-- default -->\n<div class=\"card\">\n  <ul class=\"menu\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- primary -->\n<div class=\"card\">\n  <ul class=\"menu menu-primary\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- secondary -->\n<div class=\"card\">\n  <ul class=\"menu menu-secondary\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- tertiary -->\n<div class=\"card\">\n  <ul class=\"menu menu-tertiary\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- info -->\n<div class=\"card\">\n  <ul class=\"menu menu-info\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- warning -->\n<div class=\"card\">\n  <ul class=\"menu menu-warning\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- success -->\n<div class=\"card\">\n  <ul class=\"menu menu-success\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n<!-- error -->\n<div class=\"card\">\n  <ul class=\"menu menu-error\">\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
      jsxCode: '{/* default */}\n<div className=\"card\">\n  <ul className=\"menu\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* primary */}\n<div className=\"card\">\n  <ul className=\"menu menu-primary\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* secondary */}\n<div className=\"card\">\n  <ul className=\"menu menu-secondary\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* tertiary */}\n<div className=\"card\">\n  <ul className=\"menu menu-tertiary\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* info */}\n<div className=\"card\">\n  <ul className=\"menu menu-info\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* warning */}\n<div className=\"card\">\n  <ul className=\"menu menu-warning\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* success */}\n<div className=\"card\">\n  <ul className=\"menu menu-success\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>\n\n{/* error */}\n<div className=\"card\">\n  <ul className=\"menu menu-error\">\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n  </ul>\n</div>',
    },
    'menu with different sizes': {
      htmlCode: '<!-- small -->\n<div class=\"card w-48\">\n  <ul class=\"menu menu-sm\">\n    <li class=\"menu-title\">Small</li>\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>\n\n<!-- default -->\n<div class=\"card w-56\">\n  <ul class=\"menu menu-md\">\n    <li class=\"menu-title\">default</li>\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>\n\n<!-- large -->\n<div class=\"card w-64\">\n  <ul class=\"menu menu-lg\">\n    <li class=\"menu-title\">large</li>\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>\n\n<!-- xl -->\n<div class=\"card w-72\">\n  <ul class=\"menu menu-xl\">\n    <li class=\"menu-title\">RAWR</li>\n    <li><a class=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>',
      jsxCode: '{/* small */}\n<div className=\"card w-48\">\n  <ul className=\"menu menu-sm\">\n    <li className=\"menu-title\">Small</li>\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>\n\n{/* default */}\n<div className=\"card w-56\">\n  <ul className=\"menu menu-md\">\n    <li className=\"menu-title\">default</li>\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>\n\n{/* large */}\n<div className=\"card w-64\">\n  <ul className=\"menu menu-lg\">\n    <li className=\"menu-title\">large</li>\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>\n\n{/* xl */}\n<div className=\"card w-72\">\n  <ul className=\"menu menu-xl\">\n    <li className=\"menu-title\">RAWR</li>\n    <li><a className=\"menu-active\">Link 1</a></li>\n    <li><a>Link 2</a></li>\n    <li><a>Link 3</a></li>\n    <li>\n      <details open>\n        <summary>Opened</summary>\n        <ul>\n          <li><a>Child 1</a></li>\n          <li><a>Child 2</a></li>\n        </ul>\n      </details>\n    </li>\n  </ul>\n</div>',
    },
  }
}
