import { Component } from '@angular/core';

@Component({
  selector: 'app-navigation-bar',
  templateUrl: './navigation-bar.component.html',
  styleUrls: ['./navigation-bar.component.css']
})
export class NavigationBarComponent {
  snippets = {
    'navigation bar': {
      htmlCode: '<div class=\"navbar\"> \n  <div class=\"navbar-start\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>News</a></li>\n      <li><a>Blogs</a></li>\n      <li><a>Contact Me</a></li>\n    </ul>\n  </div>\n\n  <div class=\"navbar-end\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n</div>',
      jsxCode: '<div className=\"navbar\"> \n  <div className=\"navbar-start\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>News</a></li>\n      <li><a>Blogs</a></li>\n      <li><a>Contact Me</a></li>\n    </ul>\n  </div>\n  \n  <div className=\"navbar-end\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n</div>',
    },
    'navigation bar with collapsible menu': {
      htmlCode: '<div class=\"navbar\">\n  <div class=\"navbar-start\">\n    <ul class=\"menu menu-horizontal\">\n      <li>\n        <details open>\n          <summary>\n            Menu\n            <span class=\"material-icons-round\">\n              expand_more\n            </span>\n          </summary>\n          <ul class=\"w-56\">\n            <li><a>Item 1</a></li>\n            <li><a>Item 2</a></li>\n          </ul>\n        </details>\n      </li>\n      <li><a>Updates</a></li>\n    </ul>\n  </div>\n\n  <div class=\"navbar-end\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n</div>',
      jsxCode: '<div className=\"navbar\">\n  <div className=\"navbar-start\">\n    <ul className=\"menu menu-horizontal\">\n      <li>\n        <details open>\n          <summary>\n            Menu\n            <span className=\"material-icons-round\">\n              expand_more\n            </span>\n          </summary>\n          <ul className=\"w-56\">\n            <li><a>Item 1</a></li>\n            <li><a>Item 2</a></li>\n          </ul>\n        </details>\n      </li>\n      <li><a>Updates</a></li>\n    </ul>\n  </div>\n  \n  <div className=\"navbar-end\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n</div>',
    },
    'navigation bar with dropdown menu': {
      htmlCode: '<div class=\"navbar\">\n  <div class=\"navbar-start\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>Meals</a></li>\n      <li><a>Mix \& Match</a></li>\n      <li>\n        <div class=\"dropdown\">\n          <button tabIndex=\"0\" class=\"btn btn-ghost\">\n            More\n            <span class=\"material-icons-round\">\n              expand_more\n            </span>\n          </button>\n          <div tabIndex=\"0\" class=\"dropdown-content z-[1] card\">\n            <ul class=\"menu w-56\">\n              <li><a>Link 1</a></li>\n              <li><a>Link 2</a></li>\n            </ul>\n          </div>\n        </div>\n      </li>\n    </ul>\n  </div>\n\n  <div class=\"navbar-end\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n</div>',
      jsxCode: '<div className=\"navbar\">\n  <div className=\"navbar-start\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>Meals</a></li>\n      <li><a>Mix \&amp; Match</a></li>\n      <li>\n        <div className=\"dropdown\">\n          <button tabIndex={0} className=\"btn btn-ghost\">\n            More\n            <span className=\"material-icons-round\">\n              expand_more\n            </span>\n          </button>\n          <div tabIndex={0} className=\"dropdown-content z-[1] card\">\n            <ul className=\"menu w-56\">\n              <li><a>Link 1</a></li>\n              <li><a>Link 2</a></li>\n            </ul>\n          </div>\n        </div>\n      </li>\n    </ul>\n  </div>\n  \n  <div className=\"navbar-end\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n</div>',
    },
    'navbar start, center and end': {
      htmlCode: '<div class=\"navbar\">\n  <!-- navbar start -->\n  <div class=\"navbar-start\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n\n  <!-- navbar center -->\n  <div class=\"navbar-center\">\n    <ul class=\"menu menu-horizontal\">\n      <li><a>On Sale</a></li>\n      <li><a>Bundles</a></li>\n      <li><a>Categories</a></li>\n    </ul>\n  </div>\n\n  <!-- navbar end -->\n  <div class=\"navbar-end\">\n    <ul class=\"menu menu-horizontal\">\n      <li>\n        <a class=\"btn\">\n          <span class=\"material-icons-round\">\n            shopping_cart\n          </span>\n          Shopping Cart\n        </a>\n      </li>\n    </ul>\n  </div>\n</div>',
      jsxCode: '<div className=\"navbar\">\n  {/* navbar start */}\n  <div className=\"navbar-start\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>Almost Material</a></li>\n    </ul>\n  </div>\n  \n  {/* navbar center */}\n  <div className=\"navbar-center\">\n    <ul className=\"menu menu-horizontal\">\n      <li><a>On Sale</a></li>\n      <li><a>Bundles</a></li>\n      <li><a>Categories</a></li>\n    </ul>\n  </div>\n  \n  {/* navbar end */}\n  <div className=\"navbar-end\">\n    <ul className=\"menu menu-horizontal\">\n      <li>\n        <a className=\"btn\">\n          <span className=\"material-icons-round\">\n            shopping_cart\n          </span>\n          Shopping Cart\n        </a>\n      </li>\n    </ul>\n  </div>\n</div>',
    },
    'bottom navigation bar': {
      htmlCode: '<div class=\"navbar navbar-bottom\">\n  <ul class=\"menu\">\n    <li><a class=\"menu-active\"><span class=\"material-icons-round\">home</span>home</a></li>\n    <li><a><span class=\"material-icons-round\">library_books</span>library</a></li>\n    <li><a><span class=\"material-icons-round\">favorite</span>favorites</a></li>\n    <li><a><span class=\"material-icons-round\">update</span>update</a></li>\n    <li><a><span class=\"material-icons-round\">settings</span>settings</a></li>\n  </ul>\n</div>',
      jsxCode: '<div className=\"navbar navbar-bottom\">\n  <ul className=\"menu\">\n    <li><a className=\"menu-active\"><span className=\"material-icons-round\">home</span>home</a></li>\n    <li><a><span className=\"material-icons-round\">library_books</span>library</a></li>\n    <li><a><span className=\"material-icons-round\">favorite</span>favorites</a></li>\n    <li><a><span className=\"material-icons-round\">update</span>update</a></li>\n    <li><a><span className=\"material-icons-round\">settings</span>settings</a></li>\n  </ul>\n</div>',
    },
  }
}
